version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
workflows:
  build:
    jobs:
      - run:
          command: "git clone https://github.com/Inflectra/ui-test-automation-playground.git"
      - cypress/run:
          executor: with-chrome
          browser: chrome
